# Generated by Django 2.1 on 2018-10-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181022_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='img',
            field=models.ImageField(upload_to='blog'),
        ),
    ]
