# Generated by Django 2.1 on 2018-10-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181024_2356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookImage',
        ),
    ]
