# Generated by Django 2.1 on 2018-12-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20181030_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='book'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
